### ISSUE TITLE
J2 analytic propagator

### ISSUE THREAD

**Issue by Darkissuez** [galactics/beyond#31]
Hello,

I was looking to the implementation of the J2 analytic propagator and I realized that you have:
`dM = 3 / 4 * com * np.sqrt(1 - e ** 2) * (2 - 3 * np.sin(i) ** 2)`
but according to the theory (for example in Vallado's book), shouldn't it be the symmetric of this: (-2 + 3 * np.sin(i) ** 2) ??
 
Regards

**Comment by galactics** [comment]
Hello, and thank you for opening this issue.
If I'm not doing another mistake here, I think that my formula is correct, as in Vallado's the formula 9-41 (page 652) is ![test](http://www.latex2png.com/pngs/1debdb7d6df19de8174f9b77ff4d5eb0.png) and my formula does not have a -3 as the first term, so the signs should be equivalent is Vallado's an mine.
I have also confirmed this in other books, but I may be missing something else entirely.
Could you confirm that my reasoning is correct ?

Thank you for checking for mistakes, as I'm sure I made a few

**Comment by Darkissuez** [comment]
Hello, thank you for your fast response

yet again, my old version of the book betrayed me :/ I now looked at the errata available online (https://celestrak.com/software/vallado-sw.php) and I confirm that the correct formula is the one you used.

I apologize for not having double checked my version before opening this issue.

**Comment by galactics** [comment]
No problem here, this was an honest mistake. I sure forgot to check for errata several times.
Anyway, thank you very much for caring enough to give feedback, it's really appreciated.
