### ISSUE TITLE
Latest error: ValueError: Unknown 'TLS'

### ISSUE THREAD

**Issue by yangyang-studio** [galactics/beyond#39]
![mmexport1658194387214](https://user-images.githubusercontent.com/84533790/179644843-53ce111d-cba1-456c-a24a-ca3d46227bac.png)
![mmexport1658194821483](https://user-images.githubusercontent.com/84533790/179649419-a8aafe61-f469-443e-a919-ce40f3806395.png)

Please help me to see, how to deal with my side, look forward to your reply, thank you!

**Comment by yangyang-studio** [comment]
How do I deal with this?

**Comment by galactics** [comment]
Hi @yangyang-studio !

I'm sorry but I can't help you with your problem as I can't see where the error is originating from.
Could you provide the full traceback, in a textual form ?

**Comment by yangyang-studio** [comment]
Hello, what's your email address? I will send you the code in the past, you test it here, how do I save it here, I do not know where the problem lies. Thanks

**Comment by yangyang-studio** [comment]
Hello, can I provide your email address? I'll send you all the code, please help me debug it. 
Thank you very much!
