### ISSUE TITLE
LTAN calculation

### ISSUE THREAD

**Issue by karatemir** [galactics/beyond#41]
Hi there,

I was trying to compute LTAN values for some random SSO satellites and came across your library and [orbit-predictor](https://github.com/satellogic/orbit-predictor). There is some slight discrepancy (~10 min) between your function and the aforementioned module's related function and I was wondering whether you can help me figure out the differences.

I used the following simple code to demonstrate the discrepancy:
```
from beyond.io.tle import Tle
from beyond.utils.ltan import orb2ltan, raan2ltan
from orbit_predictor.utils import ltan_from_raan
from datetime import timedelta

bee = """\
1 48884U 21059F   22271.35224498  .00012911  00000+0  65126-3 0  9996
2 48884  97.5684  40.5481 0009089 109.4705 250.7511 15.17231497 69520
"""

orb = Tle(bee).orbit()
print(orb.raan, np.rad2deg(orb.raan))
print(f'Beyond LTAN: {timedelta(seconds=orb2ltan(orb))}')

orb_cp = orb.copy(frame="EME2000", form="keplerian")
print(f'EME2000 frame  : {orb_cp.raan}, {np.rad2deg(orb_cp.raan)}')
print(f'Without EME2000: {orb.raan}, {np.rad2deg(orb.raan)}')

print(f'Beyond LTAN: {timedelta(seconds=raan2ltan(orb.date, orb_cp.raan))}')
print(f'Beyond LTAN without EME2000: {timedelta(seconds=raan2ltan(orb.date, orb.raan))}')

print('-----')

print(f'Orbit-Predictor: {timedelta(hours=ltan_from_raan(orb.date.datetime, np.rad2deg(orb.raan)))}')
print(f'Orbit-Predictor with EME2000: {timedelta(hours=ltan_from_raan(orb.date.datetime, np.rad2deg(orb_cp.raan)))}')
```
Which prints 
```
0.7076978504279127 40.5481
Beyond LTAN: 2:12:34.039055
EME2000 frame  : 0.702387824371114, 40.24385791784094
Without EME2000: 0.7076978504279127 40.5481
Beyond LTAN: 2:12:34.039055
Beyond LTAN without EME2000: 2:13:47.057154
-----
Orbit-Predictor: 2:23:03.947825
Orbit-Predictor with EME2000: 2:21:50.929725
```
Beyond basically implements `raan2ltan(orb.date, orb.copy(frame="EME2000", form="keplerian").raan, type)` as defined [here](https://github.com/galactics/beyond/blob/master/beyond/utils/ltan.py#L37) whereas orbit-predictor calculates as in [here](https://github.com/satellogic/orbit-predictor/blob/561f432ac3679396f97ee947e549369b73456e9c/orbit_predictor/utils.py#L207).

To make sure that the difference was not due to EME2000 transformation you applied, I tried using orbit-predictor with both of Beyond's raan values (TLE RAAN and post-transformation RAAN).

Kind of an orthogonal question, but do you know whether there is some online resource we can use our calculated LTAN values against satellite's LTAN values? something like celestrak but for LTAN?

Thanks for the great library!

**Comment by galactics** [comment]
Hi ! 
The main difference between orbit-predictor and beyond that I can see, is the fact that by default beyond provides the _mean local time at ascending node_, where orbit-predictor gives the _true local time at ascending node_, which is computed using the real position of the sun.
In beyond, you can compute the true LTAN, by calling `orb2ltan(orb, "true")`. By doing this, the difference between orbit-predictor and beyond drops to around 1.5 seconds, which is far better.

```python
print(f'Beyond True LTAN           : {timedelta(seconds=orb2ltan(orb, "true"))}')
print(f'Orbit-Predictor True LTAN  : {timedelta(hours=ltan_from_raan(orb.date.datetime, np.rad2deg(orb.raan)))}')
```
would yield
```
Beyond True LTAN           : 2:23:02.445967
Orbit-Predictor True LTAN  : 2:23:03.947825
```
I suspect that the remaining difference comes from the way each library compute the position of the sun. I will dig deeper into this discrepancy.

If you are interested, you can find an explanation of the difference between mean and true LTAN [here](https://en.wikipedia.org/wiki/Equation_of_time).

**Comment by karatemir** [comment]
Thanks a lot! Great catch!

Do you know which one (mean LTAN or true LTAN) is most used by launch providers or satellite operators?

I will close this for now, but if you come across any further information, please let me know.

**Comment by galactics** [comment]
I would say that satellite operators are more interested in mean LTAN, as it is a common parameter of station keeping. Same for the launch providers.

Now, if you look on the mission application side, a lot of SSO satellites are Earth observation satellites. I suspect that optic/image processing expert would need to use the true LTAN in order to take into account seasonal variation of illumination of a given scene. I don't have personal knowledge of this last bit, but that would make sense to me.
